### ISSUE TITLE
Bug: notification response is not handled when opened from terminated state

### ISSUE THREAD

**Issue by damirstuhec** [Miiha/composable-user-notifications#10]
While testing the `Example` app, I discovered a bug where the library doesn't handle app being launched from a terminated state by a push notification.

Steps to reproduce:
1. Schedule notification
2. Terminate the app
3. Tap the notification
4. Notification is not handled

I didn't yet investigate why that is so any ideas are appreciated. My guess is that the `UNUserNotificationCenterDelegate` is not constructed in time for the delegate method `userNotificationCenter(_:didReceive:withCompletionHandler:)` to be handled.

**Comment by damirstuhec** [comment]
You can see a fix for the same issue here [here](https://github.com/pointfreeco/isowords/pull/174/files).

**Comment by Miiha** [comment]
Hi @damirstuhec, thanks for raising this. I will take a look 👍

**Comment by Miiha** [comment]
@damirstuhec, can you check on main? It should now be working as expected.

**Comment by laurentaylormarshall** [comment]
@Miiha Would you mind also updating the README? I ran into this issue because the README does not have this update. Thank you!
