### ISSUE TITLE
'mock' is inaccessible due to 'internal' protection level

### ISSUE THREAD

**Issue by chris-babelbark** [Miiha/composable-user-notifications#2]
I tried to implement this library, but when I attempted to use .mock() in my View's preview, I get the above error message.

The example project doesn't build either, even after I added the ComposableUserNotifications Swift package.

I have attached a screen shot of the example project not building with a different error.

![Screen Shot 2021-03-30 at 4 17 52 PM](https://user-images.githubusercontent.com/65193174/113051099-9a3eb700-9173-11eb-983e-edbdb10d0efd.png)

**Comment by Miiha** [comment]
Hi @chris-babelbark, thanks for raising this. 
I already made the required fixes on main, but missed to released a new version.

You should be able to resolve the errors with [0.2.0](https://github.com/Miiha/composable-user-notifications/releases/tag/0.2.0).
